train:
  _target_: albumentations.Compose
  transforms:
    - _target_: albumentations.Resize
      height: 256
      width: 256
    - _target_: albumentations.HorizontalFlip
      p: 0.5
    - _target_: albumentations.VerticalFlip
      p: 0.5
    - _target_: albumentations.RandomRotate90
      p: 0.5
    - _target_: albumentations.Normalize
      mean: [0.5, 0.5, 0.5]
      std: [0.5, 0.5, 0.5]
      max_pixel_value: 255.0
    - _target_: albumentations.pytorch.ToTensorV2
  additional_targets:
    target_image: image

val:
  _target_: albumentations.Compose
  transforms:
    - _target_: albumentations.Resize
      height: 256
      width: 256
    - _target_: albumentations.Normalize
      mean: [0.5, 0.5, 0.5]
      std: [0.5, 0.5, 0.5]
      max_pixel_value: 255.0
    - _target_: albumentations.pytorch.ToTensorV2
  additional_targets:
    target_image: image

test:
  _target_: albumentations.Compose
  transforms:
    - _target_: albumentations.Resize
      height: 256
      width: 256
    - _target_: albumentations.Normalize
      mean: [0.5, 0.5, 0.5]
      std: [0.5, 0.5, 0.5]
      max_pixel_value: 255.0
    - _target_: albumentations.pytorch.ToTensorV2
  additional_targets:
    target_image: image